# 你的头像url
avatar: /avatar.jpg
favicon: /avatar.jpg

#链接图标，链接为空则不显示
link:
  github: https://github.com/yelog
  weibo: http://weibo.com/u/2307534817
  twitter:
  linkedin:
  instagram:
  mail: jaytp@qq.com


# Table of contents | 文章目录
toc:
  max_depth: 3  # 1 - 6 (h1-h6) 目录最大级数


CDN:
  jquery: //cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js
  highlight: //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js
  pjax: //cdnjs.cloudflare.com/ajax/libs/jquery.pjax/1.9.6/jquery.pjax.min.js
  animate: https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css

