# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# 你的头像url
avatar: http://dev:78/header.jpg

# Sidebar
sidebar: right
widgets:

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Table of contents | 文章目录
toc:
  list_number: true # 目录序号
  max_depth: 3  # 1 - 6 (h1-h6) 目录最大级数

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
